export const API_ENDPOINT = window.location.origin.includes('localhost') ? process.env.REACT_APP_URL : `${window.location.origin}/datxe`;
export const DEBUG_WITH_MOCK_DATA = false;

export const defaultFilters = {
    id: '',
    mParentKey: '',
    mkey: '',
    mvalue: '',
    building: '',
    roomType: '',
    room: '',
    managerReviewScore: '',
    userName: '',
    tab: '',
    isActive: '',
    fromDate: '',
    toDate: '',
    logType: '',
    logUser: '',
    oldValue: '',
    newValue: '',
    forceReload: 0,
    userReviewScore: ''
};

export const routes = {
    home: { component: 'home', path: '/', label: 'Đặt xe' },
    adminList: { component: 'adminList', path: '/admin-list', label: 'Quản trị viên', permissions: ['Permission [Car_Booking_Admin]'] },
    adminForm: { component: 'adminForm', path: '/admin-form', label: 'Quản trị viên', permissions: ['Permission [Car_Booking_Admin]'] },
    approverList: { component: 'approverList', path: '/approver-list', label: 'Người duyệt', permissions: ['Permission [Car_Booking_Admin]'] },
    approverForm: { component: 'approverForm', path: '/approver-form', label: 'Người duyệt', permissions: ['Permission [Car_Booking_Admin]'] },
    priorityApproverList: { component: 'priorityApproverList', path: '/priority-approver-list', label: 'Người duyệt ưu tiên', permissions: ['Permission [Car_Booking_Admin]'] },
    priorityApproverForm: { component: 'priorityApproverForm', path: '/priority-approver-form', label: 'Người duyệt ưu tiên', permissions: ['Permission [Car_Booking_Admin]'] },
    managerList: { component: 'managerList', path: '/manager-list', label: 'Người quản lý xe', permissions: ['Permission [Car_Booking_Admin]'] },
    managerForm: { component: 'managerForm', path: '/manager-form', label: 'Người quản lý xe', permissions: ['Permission [Car_Booking_Admin]'] },
    log: { component: 'log', path: '/log', label: 'Lịch sử hoạt động', permissions: ['Permission [Car_Booking_Admin]'] },
    config: { component: 'config', path: '/config', label: 'Cấu hình chung', permissions: ['Permission [Car_Booking_Admin]'] },
    buildingList: { component: 'buildingList', path: '/building-list', label: 'Toà nhà', permissions: ['Permission [Car_Booking_Admin]'] },
    buildingForm: { component: 'buildingForm', path: '/building-form', label: 'Toà nhà', permissions: ['Permission [Car_Booking_Admin]'] },
    departmentList: { component: 'departmentList', path: '/department-list', label: 'Phòng ban', permissions: ['Permission [Car_Booking_Admin]'] },
    departmentForm: { component: 'departmentForm', path: '/department-form', label: 'Phòng ban', permissions: ['Permission [Car_Booking_Admin]'] },
    equipmentTypeList: { component: 'equipmentTypeList', path: '/equipment-type-list', label: 'Loại thiết bị', permissions: ['Permission [Car_Booking_Admin]'] },
    equipmentTypeForm: { component: 'equipmentTypeForm', path: '/equipment-type-form', label: 'Loại thiết bị', permissions: ['Permission [Car_Booking_Admin]'] },
    equipmentList: { component: 'equipmentList', path: '/equipment-list', label: 'Thiết bị', permissions: ['Permission [Car_Booking_Admin]'] },
    equipmentForm: { component: 'equipmentForm', path: '/equipment-form', label: 'Thiết bị', permissions: ['Permission [Car_Booking_Admin]'] },
    usagePurposeList: { component: 'usagePurposeList', path: '/usage-purpose-list', label: 'Phân loại khách', permissions: ['Permission [Car_Booking_Admin]'] },
    usagePurposeForm: { component: 'usagePurposeForm', path: '/usage-purpose-form', label: 'Phân loại khách', permissions: ['Permission [Car_Booking_Admin]'] },
    roomTypeList: { component: 'roomTypeList', path: '/room-type-list', label: 'Loại xe', permissions: ['Permission [Car_Booking_Admin]'] },
    roomTypeForm: { component: 'roomTypeForm', path: '/room-type-form', label: 'Loại xe', permissions: ['Permission [Car_Booking_Admin]'] },
    roomList: { component: 'roomList', path: '/room-list', label: 'Xe', permissions: ['Permission [Car_Booking_Admin]'] },
    roomForm: { component: 'roomForm', path: '/room-form', label: 'Xe', permissions: ['Permission [Car_Booking_Admin]'] },
    approveBookingList: { component: 'approveBookingList', path: '/approve-booking-list', label: 'Duyệt đặt xe', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]'] },
    bookingCalendar: { component: 'bookingCalendar', path: '/booking-calendar', label: 'Đặt xe', permissions: ['*'] },
    searchByDemand: { component: 'searchByDemand', path: '/search-by-demand', label: 'Tìm kiếm xe', permissions: ['*'] },
    bookingList: { component: 'bookingList', path: '/booking-list', label: 'Danh sách đặt xe', permissions: ['*'] },
    bookingForm: { component: 'bookingForm', path: '/booking-form', label: 'Đặt xe', permissions: ['*'] },
    cancelBookingForm: { component: 'cancelBookingForm', path: '/cancel-booking', label: 'Huỷ đặt xe', permissions: ['*'] },
    rejectBookingForm: { component: 'rejectBookingForm', path: '/reject-booking', label: 'Từ chối đặt xe', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]'] },
    userReviewList: { component: 'userReviewList', path: '/user-review-list', label: 'Đánh giá đặt xe', permissions: ['*'] },
    userReviewForm: { component: 'userReviewForm', path: '/user-review-form', label: 'Đánh giá đặt xe', permissions: ['*'] },
    managerReviewList: { component: 'managerReviewList', path: '/manager-review-list', label: 'Đánh giá người sử dụng', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    managerReviewForm: { component: 'managerReviewForm', path: '/manager-review-form', label: 'Đánh giá người sử dụng', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    reportGuestCount: { component: 'reportGuestCount', path: '/report-guest-count', label: 'Số lượng khách', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    reportUsedCount: { component: 'reportUsedCount', path: '/report-used-count', label: 'Số lần sử dụng', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    reportCapacity: { component: 'reportCapacity', path: '/report-capacity', label: 'Công suất xe', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    reportUsageDemand: { component: 'reportUsageDemand', path: '/report-usage-demand', label: 'Nhu cầu sử dụng', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    reportManagerReview: { component: 'reportManagerReview', path: '/report-manager-review', label: 'Đánh giá người sử dụng', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    reportUserReview: { component: 'reportUserReview', path: '/report-user-review', label: 'Đánh giá đặt xe', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]', 'Permission [Car_Booking_Monitor]'] },
    carLineList: { component: 'carLineList', path: '/car-line-list', label: 'Dòng xe', permissions: ['Permission [Car_Booking_Admin]'] },
    carLineForm: { component: 'carLineForm', path: '/car-line-form', label: 'Dòng xe', permissions: ['Permission [Car_Booking_Admin]'] },
    driverList: { component: 'driverList', path: '/driver-list', label: 'Tài xế', permissions: ['Permission [Car_Booking_Admin]'] },
    driverForm: { component: 'driverForm', path: '/driver-form', label: 'Tài xế', permissions: ['Permission [Car_Booking_Admin]'] },
    approveAssignBookingForm: { component: 'approveAssignBookingForm', path: '/approve-assign-booking', label: 'Duyệt và phân công', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Approval]', 'Permission [Car_Booking_Priority_Approval]'] },
    driverConfirmBookingList: { component: 'driverConfirmBookingList', path: '/driver-confirm-booking-list', label: 'Tài xế tiếp nhận', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Driver_Confirm]'] },
    driverRejectBookingForm: { component: 'driverRejectBookingForm', path: '/driver-reject-booking', label: 'Từ chối đặt xe', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Driver_Confirm]'] },
    driverReviewForm: { component: 'driverReviewForm', path: '/driver-review-form', label: 'Tài xế đánh giá', permissions: ['Permission [Car_Booking_Admin]', 'Permission [Car_Booking_Driver_Confirm]'] },

};
