trigger:
  branches:
    include:
      - dev
      - main

pool:
  vmImage: ubuntu-24.04
  name: Default

stages:
  - stage: DevStage
    displayName: 'Development Stage'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    variables:
      group: Dev
    jobs:
      - job: DevJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: "Setup Node.js"
          - task: DownloadSecureFile@1
            inputs:
              secureFile: .env-dev
            displayName: "Download .env File"
          - task: DownloadSecureFile@1
            inputs:
              secureFile: config-dev.php
            displayName: "Download config.php File"
          - script: |
              echo "Copying .env & config.php file to root checkout folder..."
              mv $(Agent.TempDirectory)/.env-dev $(Agent.TempDirectory)/.env
              cp $(Agent.TempDirectory)/.env $(Build.SourcesDirectory)
              mv $(Agent.TempDirectory)/config-dev.php $(Agent.TempDirectory)/config.php
              cp $(Agent.TempDirectory)/config.php $(Build.SourcesDirectory)/public/api/
            displayName: "Copy .env & config.php File"
          - script: |
              echo "Installing dependencies..."
              npm install
            displayName: "Install Dependencies"
          
          - script: |
              echo "Deploying to server..."
              npm run build
            displayName: "Run Deploy"

  - stage: MainStage
    displayName: 'Main Stage'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      group: Main
    jobs:
      - job: MainJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: "Setup Node.js"
          - task: DownloadSecureFile@1
            inputs:
              secureFile: .env-main
            displayName: "Download .env File"
          - task: DownloadSecureFile@1
            inputs:
              secureFile: config-main.php
            displayName: "Download config.php File"
          - script: |
              echo "Copying .env & config.php file to root checkout folder..."
              mv $(Agent.TempDirectory)/.env-main $(Agent.TempDirectory)/.env
              cp $(Agent.TempDirectory)/.env $(Build.SourcesDirectory)
              mv $(Agent.TempDirectory)/config-main.php $(Agent.TempDirectory)/config.php
              cp $(Agent.TempDirectory)/config.php $(Build.SourcesDirectory)/public/api/
            displayName: "Copy .env & config.php File"
          - script: |
              echo "Installing dependencies..."
              npm install
            displayName: "Install Dependencies"
          
          - script: |
              echo "Deploying to server..."
              npm run build
            displayName: "Run Deploy"